name: Dependencies

on:
  schedule:
    - cron: "0 2 * * 1" # Run weekly on Mondays at 2 AM
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check for outdated packages
        run: npm outdated

      - name: Update dependencies
        run: |
          npm update
          npm audit fix

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update dependencies"
          title: "chore: update dependencies"
          body: |
            This PR updates dependencies to their latest versions.

            - [ ] Tests pass
            - [ ] No breaking changes
            - [ ] Security audit passes
          branch: update-dependencies
          delete-branch: true
